
development:
  adapter: postgresql
  encoding: unicode
  database: fireworks_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: fireworks_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fireworks_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST